package cmd

import (
	"bytes"
	"strings"
	"text/template"
	"time"
)

// templateData holds all values collected by the wizard for YAML rendering.
type templateData struct {
	GeneratedAt  string
	Slack        slackTemplateData
	Repos        []repoTemplateData
	Limits       limitsTemplateData
	Triage       triageTemplateData
	Agent        agentTemplateData
	Digest       digestTemplateData
	IssueTracker issueTrackerTemplateData
	Log          logTemplateData
}

type slackTemplateData struct {
	AppToken string
	BotToken string
	Channels []string
	Emoji    string
	Keywords []string
}

type repoTemplateData struct {
	Name          string
	Path          string
	DefaultBranch string
	Primary       bool
}

type limitsTemplateData struct {
	MaxConcurrent  int
	TimeoutMinutes int
}

type triageTemplateData struct {
	Model string
}

type agentTemplateData struct {
	Model string
}

type digestTemplateData struct {
	Enabled bool
}

type issueTrackerTemplateData struct {
	Enabled      bool
	Provider     string
	APIToken     string
	TeamID       string
	CreateIssues bool
}

type logTemplateData struct {
	Level string
}

const yamlTemplate = `# Toad configuration
# Generated by toad init — {{ .GeneratedAt }}

# ──────────────────────────────────────────────
# Slack Connection
# ──────────────────────────────────────────────
slack:
  # Tokens (can also use TOAD_SLACK_APP_TOKEN / TOAD_SLACK_BOT_TOKEN env vars)
  app_token: "{{ .Slack.AppToken }}"
  bot_token: "{{ .Slack.BotToken }}"
{{ if .Slack.Channels }}
  # Channels to monitor (use channel names, not IDs)
  channels:
{{ range .Slack.Channels }}    - "{{ . }}"
{{ end }}{{ else }}
  # Channels to monitor (use channel names, not IDs)
  # Leave empty to auto-join all public channels on startup
  # channels:
  #   - "engineering"
{{ end }}
  # What triggers Toad
  triggers:
    emoji: "{{ .Slack.Emoji }}"
    keywords:
{{ range .Slack.Keywords }}      - "{{ . }}"
{{ end }}
# ──────────────────────────────────────────────
# Repositories
# ──────────────────────────────────────────────
repos:
  # sync_minutes: 10            # Periodic git fetch interval (0 = disabled)
  list:
{{ range $i, $r := .Repos }}    - name: "{{ $r.Name }}"
      path: "{{ $r.Path }}"
{{ if $r.Primary }}      primary: true
{{ end }}      default_branch: "{{ $r.DefaultBranch }}"
      # Per-repo VCS override:
      # vcs:
      #   platform: "gitlab"
      #   host: "gitlab.company.com"
      #   bot_usernames: ["renovate-bot"]

{{ end }}
# ──────────────────────────────────────────────
# Safety Limits
# ──────────────────────────────────────────────
limits:
  max_concurrent: {{ .Limits.MaxConcurrent }}
  timeout_minutes: {{ .Limits.TimeoutMinutes }}

# ──────────────────────────────────────────────
# Triage — message classification
# ──────────────────────────────────────────────
triage:
  model: "{{ .Triage.Model }}"

# ──────────────────────────────────────────────
# Intake — bot message allowlist
# ──────────────────────────────────────────────
# intake:
#   bot_allowlist:              # Slack Bot IDs allowed into triage (e.g. Sentry, CI bots)
#     - "B0123456789"

# ──────────────────────────────────────────────
# Toad King — passive monitoring
# ──────────────────────────────────────────────
digest:
  enabled: {{ .Digest.Enabled }}
  # batch_minutes: 5           # How often to analyze batched messages
  # min_confidence: 0.95        # Minimum confidence to auto-spawn
  # max_auto_spawn_hour: 3      # Max auto-spawns per hour
  # allowed_categories: ["bug"] # Categories eligible for auto-spawn
  # max_est_size: "medium"      # Maximum estimated fix size
  # investigate_timeout_secs: 600 # Investigation time limit (default: 10 min)

# ──────────────────────────────────────────────
# Issue Tracker
# ──────────────────────────────────────────────
{{ if .IssueTracker.Enabled }}issue_tracker:
  enabled: true
  provider: "{{ .IssueTracker.Provider }}"
{{ if .IssueTracker.APIToken }}  api_token: "{{ .IssueTracker.APIToken }}"
{{ else }}  # api_token: ""              # Or use TOAD_LINEAR_API_TOKEN env var
{{ end }}{{ if .IssueTracker.TeamID }}  team_id: "{{ .IssueTracker.TeamID }}"
{{ end }}  create_issues: {{ .IssueTracker.CreateIssues }}
  # bug_label_id: ""            # Linear label ID for bugs
  # feature_label_id: ""        # Linear label ID for features
  # respect_assignees: false    # Defer to ticket assignee instead of spawning
  # stale_days: 7               # Ignore assignments older than this many days
{{ else }}# issue_tracker:
#   enabled: false
#   provider: "linear"
#   # api_token: ""              # Or use TOAD_LINEAR_API_TOKEN env var
#   # team_id: ""
#   # create_issues: false
#   # bug_label_id: ""
#   # feature_label_id: ""
#   # respect_assignees: false   # Defer to ticket assignee instead of spawning
#   # stale_days: 7              # Ignore assignments older than this many days
{{ end }}
# ──────────────────────────────────────────────
# Ticket — Linear auto-filing gate
# ──────────────────────────────────────────────
# ticket:
#   auto_file: true              # Auto-file when findings are Sentry-corroborated + confident + feasible
#   auto_file_confidence: 0.85   # Minimum confidence required to auto-file (else propose via CTA)
#   triage_state_id: ""          # Optional Linear workflow state ID for newly filed tickets

# ──────────────────────────────────────────────
# VCS Platform
# ──────────────────────────────────────────────
# vcs:
#   platform: "github"         # "github" or "gitlab"
#   # host: "gitlab.example.com"  # Self-hosted GitLab hostname (or TOAD_GITLAB_HOST env)
#   # bot_usernames:              # Usernames to treat as bots (GitLab)
#   #   - "renovate-bot"

# ──────────────────────────────────────────────
# Agent — investigation runs
# ──────────────────────────────────────────────
agent:
  platform: "claude"
  model: "{{ .Agent.Model }}"
  # append_system_prompt: ""   # Extra instructions for all agent runs
  # fallback_api_key_env: "ANTHROPIC_API_KEY"  # Env var to retry with when the CLI seat hits a usage/rate limit
  # mcp_servers:                # MCP servers available during read-only investigations
  #   sentry:
  #     url: "https://mcp.sentry.dev/mcp"
  #     auth_token_env: "SENTRY_API_TOKEN"

# ──────────────────────────────────────────────
# Logging
# ──────────────────────────────────────────────
log:
  level: "{{ .Log.Level }}"
  # file: "~/.toad/toad.log"    # Default log file location

# ──────────────────────────────────────────────
# MCP Server — Claude Desktop/Code integration
# ──────────────────────────────────────────────
# mcp:
#   enabled: false               # Enable the MCP server
#   host: "localhost"            # Hostname for the MCP endpoint
#   port: 8099                   # Port to listen on
#   devs:                        # Slack user IDs with dev access (logs tool)
#     - "U0123456789"
#   message: ""                  # Optional message included in the connect DM

`

var configTemplate = template.Must(template.New("config").Parse(yamlTemplate))

// renderConfig executes the YAML template with the provided data.
func renderConfig(data templateData) ([]byte, error) {
	if data.GeneratedAt == "" {
		data.GeneratedAt = time.Now().Format("2006-01-02")
	}

	var buf bytes.Buffer
	if err := configTemplate.Execute(&buf, data); err != nil {
		return nil, err
	}

	// Clean up excessive blank lines (3+ consecutive → 2)
	result := buf.String()
	for strings.Contains(result, "\n\n\n") {
		result = strings.ReplaceAll(result, "\n\n\n", "\n\n")
	}

	return []byte(result), nil
}
