package cmd

import (
	"bytes"
	"strings"
	"text/template"
	"time"
)

// templateData holds all values collected by the wizard for YAML rendering.
type templateData struct {
	GeneratedAt  string
	Slack        slackTemplateData
	Repos        []repoTemplateData
	Limits       limitsTemplateData
	Triage       triageTemplateData
	Agent        agentTemplateData
	Digest       digestTemplateData
	IssueTracker issueTrackerTemplateData
	Log          logTemplateData
}

type slackTemplateData struct {
	AppToken string
	BotToken string
	Channels []string
	Emoji    string
	Keywords []string
}

type repoTemplateData struct {
	Name          string
	Path          string
	TestCommand   string
	LintCommand   string
	DefaultBranch string
	AutoMerge     bool
	PRLabels      []string
	Primary       bool
}

type limitsTemplateData struct {
	MaxConcurrent   int
	MaxTurns        int
	TimeoutMinutes  int
	MaxFilesChanged int
	MaxRetries      int
}

type triageTemplateData struct {
	Model     string
	AutoSpawn bool
}

type agentTemplateData struct {
	Model string
}

type digestTemplateData struct {
	Enabled bool
	DryRun  bool
}

type issueTrackerTemplateData struct {
	Enabled      bool
	Provider     string
	APIToken     string
	TeamID       string
	CreateIssues bool
}

type logTemplateData struct {
	Level string
}

const yamlTemplate = `# Toad configuration
# Generated by toad init — {{ .GeneratedAt }}

# ──────────────────────────────────────────────
# Slack Connection
# ──────────────────────────────────────────────
slack:
  # Tokens (can also use TOAD_SLACK_APP_TOKEN / TOAD_SLACK_BOT_TOKEN env vars)
  app_token: "{{ .Slack.AppToken }}"
  bot_token: "{{ .Slack.BotToken }}"
{{ if .Slack.Channels }}
  # Channels to monitor (use channel IDs, not names)
  channels:
{{ range .Slack.Channels }}    - "{{ . }}"
{{ end }}{{ else }}
  # Channels to monitor (use channel IDs, not names)
  # Leave empty to auto-join all public channels on startup
  # channels:
  #   - "C0123456789"
{{ end }}
  # What triggers Toad
  triggers:
    emoji: "{{ .Slack.Emoji }}"
    keywords:
{{ range .Slack.Keywords }}      - "{{ . }}"
{{ end }}
# ──────────────────────────────────────────────
# Repositories
# ──────────────────────────────────────────────
repos:
  # sync_minutes: 10            # Periodic git fetch interval (0 = disabled)
  list:
{{ range $i, $r := .Repos }}    - name: "{{ $r.Name }}"
      path: "{{ $r.Path }}"
{{ if $r.Primary }}      primary: true
{{ end }}{{ if $r.TestCommand }}      test_command: "{{ $r.TestCommand }}"
{{ end }}{{ if $r.LintCommand }}      lint_command: "{{ $r.LintCommand }}"
{{ end }}      default_branch: "{{ $r.DefaultBranch }}"
      auto_merge: {{ $r.AutoMerge }}
      # merge_bot_fixups: false    # Auto-merge bot-authored PRs targeting toad branches (e.g. CI style fixes)
{{ if $r.PRLabels }}      pr_labels:
{{ range $r.PRLabels }}        - "{{ . }}"
{{ end }}{{ end }}      # Per-service validation for monorepos:
      # services:
      #   - path: "web-app"
      #     test_command: "make test"
      #     lint_command: "make stan && make cs"
      # Per-repo VCS override:
      # vcs:
      #   platform: "gitlab"
      #   host: "gitlab.company.com"
      #   bot_usernames: ["renovate-bot"]

{{ end }}
# ──────────────────────────────────────────────
# Safety Limits
# ──────────────────────────────────────────────
limits:
  max_concurrent: {{ .Limits.MaxConcurrent }}
  max_turns: {{ .Limits.MaxTurns }}
  timeout_minutes: {{ .Limits.TimeoutMinutes }}
  max_files_changed: {{ .Limits.MaxFilesChanged }}
  max_retries: {{ .Limits.MaxRetries }}
  # max_review_rounds: 3      # Max rounds of PR review fixes
  # max_ci_fix_rounds: 2      # Max rounds of CI failure fixes
  # history_size: 50          # Max completed runs to keep in state
  # worktree_ttl_hours: 24    # Auto-remove worktrees older than this (0 = disabled)

# ──────────────────────────────────────────────
# Triage — message classification
# ──────────────────────────────────────────────
triage:
  model: "{{ .Triage.Model }}"
  auto_spawn: {{ .Triage.AutoSpawn }}

# ──────────────────────────────────────────────
# Toad King — passive monitoring
# ──────────────────────────────────────────────
digest:
  enabled: {{ .Digest.Enabled }}
{{ if .Digest.Enabled }}  dry_run: {{ .Digest.DryRun }}
{{ else }}  # dry_run: true
{{ end }}  # batch_minutes: 5           # How often to analyze batched messages
  # min_confidence: 0.95        # Minimum confidence to auto-spawn
  # max_auto_spawn_hour: 3      # Max auto-spawns per hour
  # allowed_categories: ["bug"] # Categories eligible for auto-spawn
  # max_est_size: "medium"      # Maximum estimated fix size
  # investigate_timeout_secs: 600 # Investigation time limit (default: 10 min)
  # investigate_max_turns: 25     # Investigation turn limit
  # comment_investigation: false  # Post investigation findings as Slack reply (dry_run only)

# ──────────────────────────────────────────────
# Issue Tracker
# ──────────────────────────────────────────────
{{ if .IssueTracker.Enabled }}issue_tracker:
  enabled: true
  provider: "{{ .IssueTracker.Provider }}"
{{ if .IssueTracker.APIToken }}  api_token: "{{ .IssueTracker.APIToken }}"
{{ else }}  # api_token: ""              # Or use TOAD_LINEAR_API_TOKEN env var
{{ end }}{{ if .IssueTracker.TeamID }}  team_id: "{{ .IssueTracker.TeamID }}"
{{ end }}  create_issues: {{ .IssueTracker.CreateIssues }}
  # bug_label_id: ""            # Linear label ID for bugs
  # feature_label_id: ""        # Linear label ID for features
  # respect_assignees: false    # Defer to ticket assignee instead of spawning
  # stale_days: 7               # Ignore assignments older than this many days
{{ else }}# issue_tracker:
#   enabled: false
#   provider: "linear"
#   # api_token: ""              # Or use TOAD_LINEAR_API_TOKEN env var
#   # team_id: ""
#   # create_issues: false
#   # bug_label_id: ""
#   # feature_label_id: ""
#   # respect_assignees: false   # Defer to ticket assignee instead of spawning
#   # stale_days: 7              # Ignore assignments older than this many days
{{ end }}
# ──────────────────────────────────────────────
# VCS Platform
# ──────────────────────────────────────────────
# vcs:
#   platform: "github"         # "github" or "gitlab"
#   # host: "gitlab.example.com"  # Self-hosted GitLab hostname (or TOAD_GITLAB_HOST env)
#   # bot_usernames:              # Usernames to treat as bots (GitLab)
#   #   - "renovate-bot"

# ──────────────────────────────────────────────
# Agent — code generation
# ──────────────────────────────────────────────
agent:
  platform: "claude"
  model: "{{ .Agent.Model }}"
  # append_system_prompt: ""   # Extra instructions for all agent runs

# ──────────────────────────────────────────────
# Logging
# ──────────────────────────────────────────────
log:
  level: "{{ .Log.Level }}"
  # file: "~/.toad/toad.log"    # Default log file location

# ──────────────────────────────────────────────
# MCP Server — Claude Desktop/Code integration
# ──────────────────────────────────────────────
# mcp:
#   enabled: false               # Enable the MCP server
#   host: "localhost"            # Hostname for the MCP endpoint
#   port: 8099                   # Port to listen on
#   devs:                        # Slack user IDs with dev access (logs tool)
#     - "U0123456789"
#   message: ""                  # Optional message included in the connect DM

`

var configTemplate = template.Must(template.New("config").Parse(yamlTemplate))

// renderConfig executes the YAML template with the provided data.
func renderConfig(data templateData) ([]byte, error) {
	if data.GeneratedAt == "" {
		data.GeneratedAt = time.Now().Format("2006-01-02")
	}

	var buf bytes.Buffer
	if err := configTemplate.Execute(&buf, data); err != nil {
		return nil, err
	}

	// Clean up excessive blank lines (3+ consecutive → 2)
	result := buf.String()
	for strings.Contains(result, "\n\n\n") {
		result = strings.ReplaceAll(result, "\n\n\n", "\n\n")
	}

	return []byte(result), nil
}
